# Site
repository: Donadelnal/Personal_page
favicon: 

# Content configuration version
version: 2

# Personal info
name: Daniel Zalewski
title: Researcher, Bioinformatician, R programmer, Pharmacist, Laboratory Diagnostician
email: daniel.piotr.zalewski@gmail.com
website: https://donadelnal.github.io/Personal_page/
image: images/profile_image_ok_small_small.jpg

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  Donadelnal
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: Daniel Zalewski
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0002-2254-2009

# Additional icon links
additional_links:
- title: ORCID link
  icon: fab fa-orcid
  url: https://orcid.org/0000-0002-2254-2009
- title: Researchgate link
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Daniel_Zalewski29
- title: University link
  icon: fas fa-university
  url: https://umlub.pl/uczelnia/pracownicy/szczegoly,3312.html
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_image_ok_small.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Daniel and I work as a researcher in the Medical University of Lublin in Poland.
  
  In my research, I focus on the identification of transcriptomic biomarkers of peripheral vascular diseases to explain their pathogenesis and propose diagnostic and therapeutic targets. I use such technologies as Ion Torrent NGS sequencing, RT-qPCR, ELISA, and for data analysis and visualisation, I mainly use an excellent R environment.
  
  Working in innovative fields with amazing scientists allows me to make relevant discoveries, which is a great reward and a source of motivation and bravery to go further.

content:
  - title:  Academic and Research Career # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Research Assistant Professor
        sub_title: Chair and Department of Biology and Genetics, Faculty of Pharmacy, Medical University of Lublin, Poland
        caption: October 2021 - Present
        # link: http://www.umlub.pl/
        # link_text: Project Website
        # additional_links:
        # - title:  sproogen/modern-resume-theme
        #   icon: fab fa-github
        #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        #description: | # this will include new lines to allow paragraphs
        #  Chair and Department of Biology and Genetics, Faculty of Pharmacy, Medical University of Lublin, Poland
        
      - layout: top-middle
        title: Research/Didactic Assistant Professor
        sub_title: Chair and Department of Biology and Genetics, Faculty of Pharmacy, Medical University of Lublin, Poland
        caption: February 2019 - September 2021
#      - layout: top-middle
#        title: Research Assistant Professor
#        sub_title: Chair and Department of Biology and Genetics, Faculty of Pharmacy, Medical University of Lublin, Poland
#        caption: October 2021 - Present        
      - layout: top-middle
        title: Postgraduate course in Data Analysis
        sub_title: Faculty of Mathematics, Physics and Computer Science, Maria Curie-Sklodowska University in Lublin, Poland
        caption: October 2019 - September 2020
        
      - layout: top-middle
        title: PhD in Pharmacy
        sub_title: Faculty of Pharmacy, Medical University of Lublin, Poland
        caption: October 2015 - September 2019
        quote: >
          PhD thesis title: Analysis of miRNA and gene expression associated with endothelial dysfunction in patients with chronic venous insufficiency and atherosclerosis
        
      - layout: top-middle
        title: Postgraduate course in Medicinal Laboratory, Laboratory Diagnostician License
        sub_title: Faculty of Pharmacy, Medical University of Lublin, Poland
        caption: October 2017 - July 2019
        
      - layout: top-middle
        title: Pharmacist
        sub_title: Melisa pharmacy, Lublin, Poland
        caption: March 2013 - June 2015
        
      - layout: top-middle
        title: MSc in Pharmacy
        sub_title: Faculty of Pharmacy, Medical University of Lublin, Poland
        caption: October 2007 - January 2013
        quote: >
          MSc thesis title: Chromatographic analysis and study of anticancer activity of alkaloid fractions from Chelidonium majus L.
          
      - layout: top-middle
        title: Chairman of the Research Student Group "Biotechnolog"
        sub_title: Development of a new thin-layer chromatography densitometric method for quantitative and qualitative determination of the main alkaloids of Chelidonium maius L. and in vitro investigations of the anticancer activity of the alkaloids
        caption: October 2008 - September 2012
        
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content: list
#      - layout:
#        title: Miniatura
        # link: boringcompany.com
        # link_text: boringcompany.com
#        sub_title: title of project
#        caption: November 2021 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Miniatura 5
        sub_title: November 2021 - Present
        caption: 
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and #academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
         ## The analysis of microRNA expression profiles in plasma of patients with lower extremities arterial disease, abdominal aortic aneurysm and chronic venous disease - the preliminary study.
          
      - layout: left
        title: STRATEGMED 3
        sub_title: July 2018 - December 2020
        caption: 
        description: | # this will include new lines to allow paragraphs
         ## Development of optimized methods of treating tissue damage based on innovative composites and mesenchymal stem cells and their derivatives in patients with civilization diseases.
          
      - layout: left
        title: BIOSTRATEG 3
        sub_title: February 2019 - May 2019
        caption: 
        description: | # this will include new lines to allow paragraphs
         ## Bioproducts from lignocellulosic biomass derived from marginal land to fill the gap in current national bioeconomy.
          
      - layout: left
        title: Other
        sub_title: Since 2015
        caption: 
        description: | # this will include new lines to allow paragraphs
          ## Identification of miRNA, transcriptomic and proteomic biomarkers associated with human peripheral vascular diseases and their risk factors.
          ## Identification of miRNAs involved in development of glaucoma.
          ## Investigations on Alzheimer disease-related genes after stroke.
          ## Identification of genetic factors of human longevity.
          ## Identification of natural compounds with antiparasitic and anticancer activity.
          
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
     #### 2021
      - Zalewski, D.P.; Ruszel, K.P.; Stępniewski, A.; Gałkowski, D.; Bogucki, J.; Kołodziej, P.; Szymańska, J.; Płachno, B.J.; Zubilewicz, T.; Feldo, M.; et al. Identification of Transcriptomic Differences between Lower Extremities Arterial Disease, Abdominal Aortic Aneurysm and Chronic Venous Disease in Peripheral Blood Mononuclear Cells Specimens. Int J Mol Sci 2021, 22, doi:10.3390/ijms22063200. [Webpage](https://www.mdpi.com/1422-0067/22/6/3200/htm)
      - Kołodziej, P.; Nicoś, M.; Krawczyk, P.A.; Bogucki, J.; Karczmarczyk, A.; Zalewski, D.; Kubrak, T.; Kołodziej, E.; Makuch-Kocka, A.; Madej-Czerwonka, B.; et al. The Correlation of Mutations and Expressions of Genes within the PI3K/Akt/MTOR Pathway in Breast Cancer—A Preliminary Study. International Journal of Molecular Sciences 2021, 22, 2061, doi:10.3390/ijms22042061. [Webpage](https://www.mdpi.com/1422-0067/22/4/2061/htm)
      - Kosior-Jarecka, E.; Czop, M.; Gasińska, K.; Wróbel-Dudzińska, D.; Zalewski, D.P.; Bogucka-Kocka, A.; Kocki, J.; Żarnowski, T. MicroRNAs in the Aqueous Humor of Patients with Different Types of Glaucoma. Graefe’s Archive for Clinical and Experimental Ophthalmology 2021, doi:10.1007/s00417-021-05214-z. [Webpage](https://link.springer.com/article/10.1007%2Fs00417-021-05214-z)
      - Iłżecki, M.; Feldo, M.; Bogucka-Kocka, A.; Zalewski, D.; Chmiel, P.; Dave, S.; Iłżecka, J. Serum Peroxiredoxin-1 in Patients Undergoing Carotid Endarterectomy – Short Report. Acta Angiologica 2021, 27, 49–52, doi:10.5603/AA.2021.0009. [Webpage](https://journals.viamedica.pl/acta_angiologica/article/view/85467)
      - Daniel Zalewski, Przemysław Kołodziej, Anna Bogucka-Kocka. Aktywność przeciwpasożytnicza. Olejki eteryczne w profilaktyce i leczeniu chorób infekcyjnych. Red. nauk. Anna Malm, s. 72-93, Wydawnictwo Lekarskie PZWL, Warszawa, 2021. ISBN 978-83-200-6397-4. [Webpage](https://pzwl.pl/Olejki-eteryczne-w-profilaktyce-i-leczeniu-chorob-infekcyjnych,160473246,p.html)
      
     #### 2020
      - Zalewski, D.P.; Ruszel, K.P.; Stępniewski, A.; Gałkowski, D.; Bogucki, J.; Komsta, Ł.; Kołodziej, P.; Chmiel, P.; Zubilewicz, T.; Feldo, M.; et al. Dysregulations of MicroRNA and Gene Expression in Chronic Venous Disease. J Clin Med 2020, 9, doi:10.3390/jcm9051251. [Webpage](https://www.mdpi.com/2077-0383/9/5/1251/htm)
      - Zalewski, D.P.; Ruszel, K.P.; Stępniewski, A.; Gałkowski, D.; Bogucki, J.; Komsta, Ł.; Kołodziej, P.; Chmiel, P.; Zubilewicz, T.; Feldo, M.; et al. Dysregulation of MicroRNA Modulatory Network in Abdominal Aortic Aneurysm. J Clin Med 2020, 9, doi:10.3390/jcm9061974. [Webpage](https://www.mdpi.com/2077-0383/9/6/1974/htm)
      - Daniel Zalewski, Paulina Chmiel, Marcin Feldo, Anna Bogucka-Kocka. Choroba tętnic kończyn dolnych jako jedna z przyczyn niepełnosprawności osób dorosłych. Medycyna spersonalizowana 2020. Red. Anna Bogucka-Kocka, Janusz Kocki, s. 247-256, Wydawnictwo Muzyczne POLIHYMNIA Sp. z o.o., Lublin 2020. ISBN 978-83-7847-714-3
      
     #### 2019
      - Bogucka-Kocka, A.; Zalewski, D.P.; Ruszel, K.P.; Stępniewski, A.; Gałkowski, D.; Bogucki, J.; Komsta, Ł.; Kołodziej, P.; Zubilewicz, T.; Feldo, M.; et al. Dysregulation of MicroRNA Regulatory Network in Lower Extremities Arterial Disease. Front Genet 2019, 10, 1200, doi:10.3389/fgene.2019.01200. [Webpage](https://www.frontiersin.org/articles/10.3389/fgene.2019.01200/full)
      - Och, A.; Zalewski, D.; Komsta, Ł.; Kołodziej, P.; Kocki, J.; Bogucka-Kocka, A. Cytotoxic and Proapoptotic Activity of Sanguinarine, Berberine, and Extracts of Chelidonium Majus L. and Berberis Thunbergii DC. toward Hematopoietic Cancer Cell Lines. Toxins 2019, 11, 485, doi:10.3390/toxins11090485. [Webpage](https://www.mdpi.com/2072-6651/11/9/485/htm)
      - Anna Bogucka-Kocka, Przemysław Kołodziej, Daniel Zalewski, Janusz Kocki. Wpływ chorób pasożytniczych na funkcje poznawcze oraz zachowanie i rozwój dzieci. Wybrane zagadnienia z medycyny spersonalizowanej. Red. Piotr Goliszek, Andrzej Kiciński i Janusz Kocki, s. 109-118. Stowarzyszenie Absolwentów i Przyjaciół Wydziału Prawa Katolickiego Uniwersytetu Lubelskiego, Lublin, 2019. ISBN 978-83-956633-2-1.
      
     #### 2017
      - Bogucka-Kocka, A.; Zalewski, D. Qualitative and Quantitative Determination of Main Alkaloids of Chelidonium Majus L. Using Thin-Layer Chromatographic-Densitometric Method. Acta Chromatographica 2017, 29, 385–397, doi:10.1556/1326.2017.29.3.09. [webpage](https://akjournals.com/view/journals/1326/29/3/article-p385.xmla)
      
  - title: Conference presentations
    layout: text
    content: | # this will include new lines to allow paragraphs
     #### 2021
      - Zalewski, D.P.; Ruszel, K.P.; Stępniewski, A.; Gałkowski, D.; Bogucki, J.; Kołodziej, P.; Szymańska, J.; Płachno, B.J.; Zubilewicz, T.; Feldo, M.; et al. Identification of Transcriptomic Differences between Lower Extremities Arterial Disease, Abdominal Aortic Aneurysm and Chronic Venous Disease in Peripheral Blood Mononuclear Cells Specimens. Int J Mol Sci 2021, 22, doi:10.3390/ijms22063200. [Webpage](https://www.mdpi.com/1422-0067/22/6/3200/htm)
      - Kołodziej, P.; Nicoś, M.; Krawczyk, P.A.; Bogucki, J.; Karczmarczyk, A.; Zalewski, D.; Kubrak, T.; Kołodziej, E.; Makuch-Kocka, A.; Madej-Czerwonka, B.; et al. The Correlation of Mutations and Expressions of Genes within the PI3K/Akt/MTOR Pathway in Breast Cancer—A Preliminary Study. International Journal of Molecular Sciences 2021, 22, 2061, doi:10.3390/ijms22042061. [Webpage](https://www.mdpi.com/1422-0067/22/4/2061/htm)
      - Kosior-Jarecka, E.; Czop, M.; Gasińska, K.; Wróbel-Dudzińska, D.; Zalewski, D.P.; Bogucka-Kocka, A.; Kocki, J.; Żarnowski, T. MicroRNAs in the Aqueous Humor of Patients with Different Types of Glaucoma. Graefe’s Archive for Clinical and Experimental Ophthalmology 2021, doi:10.1007/s00417-021-05214-z. [Webpage](https://link.springer.com/article/10.1007%2Fs00417-021-05214-z)
      - Iłżecki, M.; Feldo, M.; Bogucka-Kocka, A.; Zalewski, D.; Chmiel, P.; Dave, S.; Iłżecka, J. Serum Peroxiredoxin-1 in Patients Undergoing Carotid Endarterectomy – Short Report. Acta Angiologica 2021, 27, 49–52, doi:10.5603/AA.2021.0009. [Webpage](https://journals.viamedica.pl/acta_angiologica/article/view/85467)
      - Daniel Zalewski, Przemysław Kołodziej, Anna Bogucka-Kocka. Aktywność przeciwpasożytnicza. Olejki eteryczne w profilaktyce i leczeniu chorób infekcyjnych. Red. nauk. Anna Malm, s. 72-93, Wydawnictwo Lekarskie PZWL, Warszawa, 2021. ISBN 978-83-200-6397-4. [Webpage](https://pzwl.pl/Olejki-eteryczne-w-profilaktyce-i-leczeniu-chorob-infekcyjnych,160473246,p.html)
      
     #### 2020
      - Zalewski, D.P.; Ruszel, K.P.; Stępniewski, A.; Gałkowski, D.; Bogucki, J.; Komsta, Ł.; Kołodziej, P.; Chmiel, P.; Zubilewicz, T.; Feldo, M.; et al. Dysregulations of MicroRNA and Gene Expression in Chronic Venous Disease. J Clin Med 2020, 9, doi:10.3390/jcm9051251. [Webpage](https://www.mdpi.com/2077-0383/9/5/1251/htm)
      - Zalewski, D.P.; Ruszel, K.P.; Stępniewski, A.; Gałkowski, D.; Bogucki, J.; Komsta, Ł.; Kołodziej, P.; Chmiel, P.; Zubilewicz, T.; Feldo, M.; et al. Dysregulation of MicroRNA Modulatory Network in Abdominal Aortic Aneurysm. J Clin Med 2020, 9, doi:10.3390/jcm9061974. [Webpage](https://www.mdpi.com/2077-0383/9/6/1974/htm)
      - Daniel Zalewski, Paulina Chmiel, Marcin Feldo, Anna Bogucka-Kocka. Choroba tętnic kończyn dolnych jako jedna z przyczyn niepełnosprawności osób dorosłych. Medycyna spersonalizowana 2020. Red. Anna Bogucka-Kocka, Janusz Kocki, s. 247-256, Wydawnictwo Muzyczne POLIHYMNIA Sp. z o.o., Lublin 2020. ISBN 978-83-7847-714-3
      
     #### 2019
      - Bogucka-Kocka, A.; Zalewski, D.P.; Ruszel, K.P.; Stępniewski, A.; Gałkowski, D.; Bogucki, J.; Komsta, Ł.; Kołodziej, P.; Zubilewicz, T.; Feldo, M.; et al. Dysregulation of MicroRNA Regulatory Network in Lower Extremities Arterial Disease. Front Genet 2019, 10, 1200, doi:10.3389/fgene.2019.01200. [Webpage](https://www.frontiersin.org/articles/10.3389/fgene.2019.01200/full)
      - Och, A.; Zalewski, D.; Komsta, Ł.; Kołodziej, P.; Kocki, J.; Bogucka-Kocka, A. Cytotoxic and Proapoptotic Activity of Sanguinarine, Berberine, and Extracts of Chelidonium Majus L. and Berberis Thunbergii DC. toward Hematopoietic Cancer Cell Lines. Toxins 2019, 11, 485, doi:10.3390/toxins11090485. [Webpage](https://www.mdpi.com/2072-6651/11/9/485/htm)
      - Anna Bogucka-Kocka, Przemysław Kołodziej, Daniel Zalewski, Janusz Kocki. Wpływ chorób pasożytniczych na funkcje poznawcze oraz zachowanie i rozwój dzieci. Wybrane zagadnienia z medycyny spersonalizowanej. Red. Piotr Goliszek, Andrzej Kiciński i Janusz Kocki, s. 109-118. Stowarzyszenie Absolwentów i Przyjaciół Wydziału Prawa Katolickiego Uniwersytetu Lubelskiego, Lublin, 2019. ISBN 978-83-956633-2-1.
      
     #### 2017
      - Bogucka-Kocka, A.; Zalewski, D. Qualitative and Quantitative Determination of Main Alkaloids of Chelidonium Majus L. Using Thin-Layer Chromatographic-Densitometric Method. Acta Chromatographica 2017, 29, 385–397, doi:10.1556/1326.2017.29.3.09. [webpage](https://akjournals.com/view/journals/1326/29/3/article-p385.xmla)
      


      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
